CLASSIFICATION_CATEGORIES: list = [
    "Spa",
    "Religion",
    "Group request",
    "Connecting  rooms",
    "Disabled",
    "Bar",
    "Parking",
    "Specific room request",
    "Quiet room",
    "Jobs",
    "Boat dock",
    "Balcony",
    "Baby",
    "Reservation modification",
    "Reservation cancellation",
    "Complaint",
    "Reservation confirmation",
    "Flight + hotel",
    "Long Stay",
    "Coworking",
    "Day use",
    "Shuttle",
    "Store luggage",
    "Social request",
    "Rooftop",
    "Restaurant",
    "Taxi",
    "Celebration",
    "Mice",
    "Concierge",
    "Housekeeping",
    "Breakfast",
    "Smoker",
    "Travel agent",
    "Bedding pillow mattress",
    "Special request",
    "Check out",
    "Payment method",
    "Discount",
    "Rentals",
    "Special diet",
    "Family",
    "Reservation",
    "Contact staff",
    "Fallback",
    "Gym",
    "Tennis",
    "Other"
]